version: '2'
services:
  sampleapp-app:
    image: sampleapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sampleapp-postgresql:5432/sampleapp
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://sampleapp-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://sampleapp-elasticsearch:9200
    ports:
      - 8080:8080
  sampleapp-postgresql:
    extends:
      file: postgresql.yml
      service: sampleapp-postgresql
  sampleapp-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: sampleapp-elasticsearch
