version: '2'
services:
  sampleapp-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/sampleapp/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sampleapp
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
